name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: |
          if (${{ runner.os }} -eq "Windows") {
            npm run build:win
          } elseif (${{ runner.os }} -eq "macOS") {
            npm run build:mac
          } else {
            npm run build:linux
          }
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/*
          token: ${{ secrets.GITHUB_TOKEN }}
